### ISSUE TITLE
Bug: starswith is not being respecting in the workflow.

### ISSUE THREAD

**Issue by bdougie** [bdougie/awesome-black-developers#19]
https://github.com/bdougie/awesome-black-developers/tree/main/.github/workflows

    if: startsWith(${{ github.event.issue.title }}, "Add handle")

should be

    if: startsWith( "Add handle", ${{ github.event.issue.title }})

**Comment by damaneice** [comment]
Great catch!

**Comment by damaneice** [comment]
It looks like it should be `if: ${{ startsWith(github.event.issue.title, 'Add handle') }}`
