### ISSUE TITLE
Add handle developerayo

### ISSUE THREAD

**Issue by Developerayo** [bdougie/awesome-black-developers#22]
### developerayo
 * DevRelChat ([podcast](https://devrelchat.dev/))
 * unStack Africa ([community](http://unstack.africa/))
 * Lazy Loading images progressively and bundle analyzing in Webpack ([video](https://youtu.be/_Enq6G2gyks))

**Comment by bdougie** [comment]
@Developerayo do you have blog posts that share your experience as a developer?

**Comment by bdougie** [comment]
nvm, your video is great. I also edited the issue a bit to work with the GitHub Action. It didn't need the link or the @
