### ISSUE TITLE
Add handle bcdbuddy

### ISSUE THREAD

**Issue by bcdbuddy** [bdougie/awesome-black-developers#25]
### bcdbuddy
  * "Website" ([http://babacar-cisse-dia.com/](http://babacar-cisse-dia.com/))
  * "Dev.to" ([profile](https://dev.to/bcdbuddy))

**Comment by bdougie** [comment]
@bcdbuddy thanks for you opening the issue and following the template. Are you able to links that represent your work, like a blog post, conference talk, or video?

Please see the README for examples.

**Comment by bcdbuddy** [comment]
I've read the README. On my website you can see my work and on [dev.to](dev.to) you can see some of my published blog posts. The drafts are available at [bcdbuddy.github.io](bcdbuddy.github.io)

Does this meet your expectations ?

**Comment by bdougie** [comment]
https://github.com/bdougie/awesome-black-developers/blob/main/CONTRIBUTING.md#contributing

I am willing to make an exception for the GitHub Sponsors requirement since it is only available in 32 regions. Providing a link to your story is better than a link to a website. Considering sharing an additional link that shares your experience. 

```
Criteria to add a developer:
* Content is about the experience of being the developer.
* The author of the content is describing their own experience.
* Projects linked must be open sourced and/or non-profit.
* Must have [GitHub Sponsors](https://github.com/sponsors/) enabled.
```

**Comment by bcdbuddy** [comment]
Oh I see. I have two open source projects:  (not being used by everyone though)
- https://github.com/bcdbuddy/carousel-slider
- https://github.com/bcdbuddy/validator

I am not sure that I have a content describing my experience as developer or my own experience. I'll work on that some day in the future. I won't mind if you close this issue. Nice chat :+1:

**Comment by bdougie** [comment]
Looking forward to reading your content.
